# Generated by Django 3.0.12 on 2021-05-18 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditor',
            name='job',
            field=models.CharField(default='стажер', max_length=20),
            preserve_default=False,
        ),
    ]
