# Generated by Django 3.0.12 on 2021-05-17 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auditor', '0001_initial'),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docsgroup', models.CharField(max_length=10)),
                ('unit', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DocsRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=30)),
                ('client_num', models.PositiveIntegerField()),
                ('reason', models.CharField(max_length=500)),
                ('docsgroup', models.CharField(max_length=10)),
                ('audit_file', models.CharField(max_length=500)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('date', models.DateField(auto_now=True)),
                ('request_by_auditor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auditor.Auditor')),
                ('request_by_client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='client.Client')),
            ],
        ),
    ]
