# Generated by Django 3.0.12 on 2021-05-18 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docsrequest',
            name='request_by_auditor',
        ),
    ]
