# Generated by Django 3.0.12 on 2021-05-18 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0002_auditor_job'),
        ('docs', '0002_remove_docsrequest_request_by_auditor'),
    ]

    operations = [
        migrations.AddField(
            model_name='docsrequest',
            name='request_by_auditor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auditor.Auditor'),
        ),
    ]
