# Generated by Django 3.0.12 on 2021-05-26 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0003_docsrequest_request_by_auditor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='docsgroup',
            field=models.CharField(max_length=20),
        ),
    ]
